// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-vibes/CivicDocument.tsx": () => import("../components/mockups/landing-vibes/CivicDocument.tsx"),
  "./components/mockups/landing-vibes/GardenMorning.tsx": () => import("../components/mockups/landing-vibes/GardenMorning.tsx"),
  "./components/mockups/landing-vibes/NightDesk.tsx": () => import("../components/mockups/landing-vibes/NightDesk.tsx")
};
